using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Zodiac
{
    class Program
    {
        static void Main(string[] args)
        {

            int dia, mes;


                Console.Write("Em que mes você nasceu?");
                if (!Int32.TryParse(Console.ReadLine(), out mes))
                Console.Write("Valor invalido\n");
                Console.Write ("Em que dia voce nasceu?");
                if (!Int32.TryParse(Console.ReadLine(), out dia))
                Console.Write("Valor invalido\n");




            switch (mes)
            {

                case 1:

                    if (dia >= 21)
                        Console.WriteLine("Aquario: Você, definitivamente, pensa fora da caixa! Não há na galáxia um signo mais inventivo e visionário do que o seu. Dizem que os aquarianos têm excesso de futuro na cabeça: é verdade! Você enxerga lá na frente, planeja reformar o mundo, quer transformar todas as crenças superadas, e também renovar a mente das pessoas – por que não? Ao seu lado, há duas armas importantes: a tecnologia (sua paixão!) e seu poderoso radar interno, que lhe indica a hora de virar a mesa. E como você vira a mesa, Aquário! Mas o que impulsiona seu espírito? É a possibilidade de implantar o novo, seja no trabalho ou na vida comunitária. A creche do seu bairro está lotada de dificuldades? É você quem procura os políticos, aciona a imprensa ou funda uma ONG. De quebra, movimenta a vizinhança para agregar novos “soldados” a essa batalha. No emprego, há uma tarefa emperrada no quesito qualidade? Pois é você quem descasca o abacaxi para resolver o problema de vez, nem que para isso seja preciso contestar seu chefe. Essa postura original e intuitiva é o que leva seu signo a ser apontado como o mais revolucionário do Zodíaco – e também o mais rebelde. Está certo que seus argumentos têm excelentes fundamentos. O que pega, talvez, seja sua forma de se posicionar. Aquário é um signo sincero, que não se curva às formalidades sociais. Então, anote: colheradas de psicologia e diplomacia poderiam tornar sua artilharia verbal mais eficiente, viu? E a “culpa” disso tudo? É de Urano, seu planeta regente. Esse astro inspira sua independência e sua capacidade mental, que é mais rápida do que a velocidade da luz!\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Capricornio: A obstinação é uma palavra que define seu jeito de ser. Porque não há, no mundo, um obstáculo que derrube sua tenacidade, sua perseverança, sua vontade de vencer. Requisitos não lhe faltam: você é uma pessoa prudente, confiável, competente, controlada. Sabe onde pisa, calcula com precisão a largura do seu passo, tem noção exata do que deseja alcançar. Por isso, o trabalho é uma das prioridades da sua vida. É numa profissão que você despeja sua notável capacidade de realização, que consiste em construir e desenvolver ideias, projetos e processos. Tudo isso pode até ser idealizado por terceiros, não tem importância. Seu negócio é colocar a mão na massa, levantar valores, definir recursos, determinar prazos, projetar resultados. Você é quem faz um sonho virar realidade. Sem a força capricorniana, um propósito no papel é só uma possibilidade. Sob o seu comando, as coisas se concretizam, acontecem. Capricórnio é como o gerente da vida! E esse papel de gerente da vida não é gratuito. Seu astro regente é Saturno, o planeta do tempo, da ponderação, da responsabilidade. Esse astro inspira sua maturidade e grita aquele ditado popular na sua alma: “A paciência é a mãe de todas as virtudes!”. Ou seja, com calma, precisão e foco, é possível conquistar o mundo! É claro que isso amplifica sua ambição. Você sonha com poder e sucesso, inclusive material. Mas essa sede de vencer tem um preço: a repressão das suas emoções. Sua fama de signo frio e calculista vem daí. Claro que essa fama é exagerada, Capricórnio, mas sempre é tempo de renovar sua bagagem emocional. O segredo da sua felicidade integral pode morar aí.\n fonte: Joao Bidu");
                    break;

                case 2:

                    if (dia >= 19)
                        Console.WriteLine("Peixes: Seu mundo interior é vasto, assim como sua facilidade de perceber o outro. Mas não se trata de identificar cor do cabelo, modelo de roupa, jeito de andar, nada disso! Você tem uma capacidade impressionante de decifrar a alma humana. É como se seus olhos viessem com um bônus: o recurso da radiografia. Nada escapa à sua percepção, ao seu sexto sentido, à força da sua imaginação. Além de talento para reconhecer as dores e as alegrias dos outros, você também tem um sensor interno capaz de avaliar o astral dos ambientes. Se eles estiverem carregados, não é incomum você se sentir mal, com o tanque da energia na reserva, sabe? É como se você absorvesse as vibrações dos lugares e das pessoas, mesmo sem querer, tipo uma esponja! Por isso, a Astrologia reconhece em Peixes habilidades premonitórias. Puxe pela memória: quantas vezes você já sonhou com coisas que se concretizaram depois? Ou teve certeza de que o celular iria tocar, e ele tocou? Já tomou uma decisão com base num pressentimento? Tudo isso é corriqueiro para o seu signo, sobretudo para os piscianos que se esforçam para expandir a própria espiritualidade. Agradeça a Netuno: é seu planeta regente que estimula sua sensibilidade, seus sentimentos profundos e sua notável criatividade. Quando esse astro se une à Água, elemento que governa seu signo, a afetividade inunda seu astral! E inclui um componente extra: a propensão à fantasia. Muitas vezes, você trafega entre esses dois mundos, a realidade e o sonho. Isso acelera o motor da sua imaginação, mas também pode trazer decepções.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Aquario: Você, definitivamente, pensa fora da caixa! Não há na galáxia um signo mais inventivo e visionário do que o seu. Dizem que os aquarianos têm excesso de futuro na cabeça: é verdade! Você enxerga lá na frente, planeja reformar o mundo, quer transformar todas as crenças superadas, e também renovar a mente das pessoas – por que não? Ao seu lado, há duas armas importantes: a tecnologia (sua paixão!) e seu poderoso radar interno, que lhe indica a hora de virar a mesa. E como você vira a mesa, Aquário! Mas o que impulsiona seu espírito? É a possibilidade de implantar o novo, seja no trabalho ou na vida comunitária. A creche do seu bairro está lotada de dificuldades? É você quem procura os políticos, aciona a imprensa ou funda uma ONG. De quebra, movimenta a vizinhança para agregar novos “soldados” a essa batalha. No emprego, há uma tarefa emperrada no quesito qualidade? Pois é você quem descasca o abacaxi para resolver o problema de vez, nem que para isso seja preciso contestar seu chefe. Essa postura original e intuitiva é o que leva seu signo a ser apontado como o mais revolucionário do Zodíaco – e também o mais rebelde. Está certo que seus argumentos têm excelentes fundamentos. O que pega, talvez, seja sua forma de se posicionar. Aquário é um signo sincero, que não se curva às formalidades sociais. Então, anote: colheradas de psicologia e diplomacia poderiam tornar sua artilharia verbal mais eficiente, viu? E a “culpa” disso tudo? É de Urano, seu planeta regente. Esse astro inspira sua independência e sua capacidade mental, que é mais rápida do que a velocidade da luz!\n fonte: Joao Bidu");
                    break;

                case 3:

                    if (dia >= 21)
                        Console.WriteLine("Aries: Áries é o primeiro signo do Zodíaco, o que explica muita coisa sobre a sua vibrante personalidade. Você gosta de decidir, dominar o romance, liderar sua equipe de trabalho. Adora dar sua opinião antes de todo mundo, ser orador da turma, subir mais alto no pódio ao fim de uma competição. Vencer – mesmo que seja num jogo de cartas. O triunfo faz bem ao seu espírito, assim como a independência. Por causa dela, você toma decisões e assume os riscos, caso alguma coisa escape do seu controle. Para isso, é preciso coragem, e essa virtude você tem de sobra! Esse seu apetite pela vida lembra o de um herói, que vive mil aventuras antes de saborear a vitória ou o final feliz com quem ama. Exatamente como o herói, você parte pra cima, enfrenta seus inimigos e também toma uns solavancos de vez em quando, porque nem tudo é perfeito. Mas não se abata, porque sua força interior é gigante, mesmo que em alguns momentos você não tenha consciência disso. Toda essa energia barulhenta vem de Marte, que é seu planeta regente. É esse astro que lhe empresta poder, agilidade, carisma, impetuosidade. O planeta vermelho também atiça sua competitividade, que se revela no trabalho e no romance. Se no ambiente profissional houver uma disputa, Áries luta com unhas e dentes para conseguir o prêmio principal. No amor, também se esforça para laçar seu alvo, até esmagar a concorrência. É como o carneiro que simboliza seu signo: você avança e impressiona pela valentia. Ainda que precise dar umas cabeçadas nos rivais, parte para cima sem medo. Medo, aliás, é uma palavra riscada do seu dicionário pessoal!\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Peixes: Seu mundo interior é vasto, assim como sua facilidade de perceber o outro. Mas não se trata de identificar cor do cabelo, modelo de roupa, jeito de andar, nada disso! Você tem uma capacidade impressionante de decifrar a alma humana. É como se seus olhos viessem com um bônus: o recurso da radiografia. Nada escapa à sua percepção, ao seu sexto sentido, à força da sua imaginação. Além de talento para reconhecer as dores e as alegrias dos outros, você também tem um sensor interno capaz de avaliar o astral dos ambientes. Se eles estiverem carregados, não é incomum você se sentir mal, com o tanque da energia na reserva, sabe? É como se você absorvesse as vibrações dos lugares e das pessoas, mesmo sem querer, tipo uma esponja! Por isso, a Astrologia reconhece em Peixes habilidades premonitórias. Puxe pela memória: quantas vezes você já sonhou com coisas que se concretizaram depois? Ou teve certeza de que o celular iria tocar, e ele tocou? Já tomou uma decisão com base num pressentimento? Tudo isso é corriqueiro para o seu signo, sobretudo para os piscianos que se esforçam para expandir a própria espiritualidade. Agradeça a Netuno: é seu planeta regente que estimula sua sensibilidade, seus sentimentos profundos e sua notável criatividade. Quando esse astro se une à Água, elemento que governa seu signo, a afetividade inunda seu astral! E inclui um componente extra: a propensão à fantasia. Muitas vezes, você trafega entre esses dois mundos, a realidade e o sonho. Isso acelera o motor da sua imaginação, mas também pode trazer decepções.\n fonte: Joao Bidu");
                    break;

                case 4:

                    if (dia >= 21)
                        Console.WriteLine("Touro: A frase “Devagar se vai ao longe” deveria fazer parte do seu RG. Porque você definitivamente acredita nisso: força, foco e fé empurram a gente pra frente, transformam nossos sonhos em realidade. Assim, você traça suas metas com critério, observa tudo com cuidado e, por ser uma pessoa prudente, demora para tomar decisões. Mas, pessoalmente, não acha que leva tanto tempo assim para se decidir. Afinal, resoluções são coisas sérias, não podem voar ao sabor do vento. No fundo, gosta bastante da sua sensatez, já que você não chegou a esse mundo para brincar, certo? E qual o propósito disso tudo? É viver uma vida extraordinária! Mas não com perigos, riscos, mudanças e aventuras, nada disso! Você sonha com uma casa linda e deliciosa, mesa farta, carro potente, boas roupas, ótimas viagens, momentos memoráveis ao lado de gente querida. E sabe que, para conquistar tudo isso, é preciso ralar. E você não foge da raia, Touro. Trabalha duro e sabe enfrentar cada dificuldade de cabeça erguida, porque tem uma extraordinária fortaleza interior e confia demais nas suas capacidades, mesmo que não faça propaganda delas. Essa natureza reservada sintetiza o perfil taurino, assim como a inclinação para perceber as coisas bonitas e prazerosas da vida. A afinidade com o belo vem do seu planeta regente, que é Vênus. Considerado o astro do amor, da beleza e das artes, Vênus planta sentimentos duradouros no seu coração. Por isso, quando se apaixona, você quase nunca se engana: é amor de verdade! E precisa ser correspondido para o romance decolar e durar o tempo que você julga adequado: até o fim da vida – e um pouco mais.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Aries: Áries é o primeiro signo do Zodíaco, o que explica muita coisa sobre a sua vibrante personalidade. Você gosta de decidir, dominar o romance, liderar sua equipe de trabalho. Adora dar sua opinião antes de todo mundo, ser orador da turma, subir mais alto no pódio ao fim de uma competição. Vencer – mesmo que seja num jogo de cartas. O triunfo faz bem ao seu espírito, assim como a independência. Por causa dela, você toma decisões e assume os riscos, caso alguma coisa escape do seu controle. Para isso, é preciso coragem, e essa virtude você tem de sobra! Esse seu apetite pela vida lembra o de um herói, que vive mil aventuras antes de saborear a vitória ou o final feliz com quem ama. Exatamente como o herói, você parte pra cima, enfrenta seus inimigos e também toma uns solavancos de vez em quando, porque nem tudo é perfeito. Mas não se abata, porque sua força interior é gigante, mesmo que em alguns momentos você não tenha consciência disso. Toda essa energia barulhenta vem de Marte, que é seu planeta regente. É esse astro que lhe empresta poder, agilidade, carisma, impetuosidade. O planeta vermelho também atiça sua competitividade, que se revela no trabalho e no romance. Se no ambiente profissional houver uma disputa, Áries luta com unhas e dentes para conseguir o prêmio principal. No amor, também se esforça para laçar seu alvo, até esmagar a concorrência. É como o carneiro que simboliza seu signo: você avança e impressiona pela valentia. Ainda que precise dar umas cabeçadas nos rivais, parte para cima sem medo. Medo, aliás, é uma palavra riscada do seu dicionário pessoal!\n fonte: Joao Bidu");
                    break;

                case 5:

                    if (dia >= 21)
                        Console.WriteLine("Gemeos: Dentro das suas veias, correm a curiosidade, a energia, o desejo de movimento, a inquietação. Você não para nunca: está sempre em busca de informações para compreender as pessoas, as coisas e as situações. Mas não fica numa estação apenas: quer correr o mundo, porque é uma pessoa ansiosa, esperta, versátil, de raciocínio rápido e com asas nos pés. A timidez é uma característica que, em geral, passa longe do seu temperamento, Gêmeos. Você conversa com todo mundo, adora descobrir novidades e faz da comunicação a sua marca pessoal. Seja falando, telefonando ou escrevendo, está sempre se expressando, perguntando, debatendo. Não é raro fazer duas coisas ao mesmo tempo (ler e ouvir música; cozinhar e falar ao celular; ver TV e completar palavras cruzadas), porque é preciso drenar esse oceano de adrenalina, certo? E tem mais: é muito fácil se sentir à vontade ao seu lado, porque você tem a exímia capacidade de quebrar o gelo na hora, e de emprestar para quem quiser os óculos do otimismo com os quais enxerga a realidade e os corações humanos. Por isso tudo, acumula um milhão de amigos, além de parceiros, “brothers”, colegas, conhecidos, companheiros, camaradas e toda a sorte de classificações para as amizades. Essa personalidade expansiva é presente de Mercúrio, seu planeta regente. Na mitologia, Mercúrio é o mensageiro do céu – é quem faz a ponte entre deuses e homens. Não por acaso, esse é o seu papel: comunicar ideias, participar, “borboletear”, ou seja, voar daqui pra lá e de lá para cá, sempre de olho em tudo o que possa saciar a sua inesgotável curiosidade.\n fonte: Joao Bidu ");
                    else
                        Console.WriteLine("Touro: A frase “Devagar se vai ao longe” deveria fazer parte do seu RG. Porque você definitivamente acredita nisso: força, foco e fé empurram a gente pra frente, transformam nossos sonhos em realidade. Assim, você traça suas metas com critério, observa tudo com cuidado e, por ser uma pessoa prudente, demora para tomar decisões. Mas, pessoalmente, não acha que leva tanto tempo assim para se decidir. Afinal, resoluções são coisas sérias, não podem voar ao sabor do vento. No fundo, gosta bastante da sua sensatez, já que você não chegou a esse mundo para brincar, certo? E qual o propósito disso tudo? É viver uma vida extraordinária! Mas não com perigos, riscos, mudanças e aventuras, nada disso! Você sonha com uma casa linda e deliciosa, mesa farta, carro potente, boas roupas, ótimas viagens, momentos memoráveis ao lado de gente querida. E sabe que, para conquistar tudo isso, é preciso ralar. E você não foge da raia, Touro. Trabalha duro e sabe enfrentar cada dificuldade de cabeça erguida, porque tem uma extraordinária fortaleza interior e confia demais nas suas capacidades, mesmo que não faça propaganda delas. Essa natureza reservada sintetiza o perfil taurino, assim como a inclinação para perceber as coisas bonitas e prazerosas da vida. A afinidade com o belo vem do seu planeta regente, que é Vênus. Considerado o astro do amor, da beleza e das artes, Vênus planta sentimentos duradouros no seu coração. Por isso, quando se apaixona, você quase nunca se engana: é amor de verdade! E precisa ser correspondido para o romance decolar e durar o tempo que você julga adequado: até o fim da vida – e um pouco mais.\n fonte: Joao Bidu");
                    break;

                case 6:

                    if (dia >= 21)
                        Console.WriteLine("Cancer: Sensibilidade, sentimento, saudosismo, intuição, proteção: todas essas cores desenham o seu DNA, Câncer! São as emoções que dão forma aos seus projetos e apontam caminhos, indicando quando e como agir. Portanto, para ser feliz, é imprescindível que o tanque do amor esteja sempre cheio. Amor, no caso, não é apenas o romântico, embora esse tenha um papel fundamental na sua trajetória. De fato, você só se realiza quando encontra sua alma gêmea, mas as outras expressões de afeto também importam, porque ajudam a construir os alicerces da sua felicidade. Assim, se não houver união e carinho no ninho familiar e junto aos seus amigos queridos, nada feito! Seu desejo de segurança afetiva é urgente, porque, sem ela, você perde uma parte significativa da sua identidade. E isso é muito sério. Por isso, seu ideal de vida é curtir uma atmosfera de acolhimento, trocando vibrações de ternura e proteção com quem mora na suíte presidencial do seu coração: mãe, pai, filhos, parceiro(a), irmãos, avós, amigos. Essa natureza sentimental e tão ricamente sensível é um oferecimento da Lua: esse astro, de essência feminina, é quem rege o seu signo. Assim como as fases lunares, seu humor é mutável, bem como a direção da sua energia. De vez em quando, você adora ficar no meio da galera. Outras vezes, prefere se trancar no quarto para meditar. Como o caranguejo que simboliza seu signo, você gruda as pinças na areia para se sentir em casa, junto às raízes, pertinho da água. A mesma Água que embala seus sonhos e conforta sua alma.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Gemeos: Dentro das suas veias, correm a curiosidade, a energia, o desejo de movimento, a inquietação. Você não para nunca: está sempre em busca de informações para compreender as pessoas, as coisas e as situações. Mas não fica numa estação apenas: quer correr o mundo, porque é uma pessoa ansiosa, esperta, versátil, de raciocínio rápido e com asas nos pés. A timidez é uma característica que, em geral, passa longe do seu temperamento, Gêmeos. Você conversa com todo mundo, adora descobrir novidades e faz da comunicação a sua marca pessoal. Seja falando, telefonando ou escrevendo, está sempre se expressando, perguntando, debatendo. Não é raro fazer duas coisas ao mesmo tempo (ler e ouvir música; cozinhar e falar ao celular; ver TV e completar palavras cruzadas), porque é preciso drenar esse oceano de adrenalina, certo? E tem mais: é muito fácil se sentir à vontade ao seu lado, porque você tem a exímia capacidade de quebrar o gelo na hora, e de emprestar para quem quiser os óculos do otimismo com os quais enxerga a realidade e os corações humanos. Por isso tudo, acumula um milhão de amigos, além de parceiros, “brothers”, colegas, conhecidos, companheiros, camaradas e toda a sorte de classificações para as amizades. Essa personalidade expansiva é presente de Mercúrio, seu planeta regente. Na mitologia, Mercúrio é o mensageiro do céu – é quem faz a ponte entre deuses e homens. Não por acaso, esse é o seu papel: comunicar ideias, participar, “borboletear”, ou seja, voar daqui pra lá e de lá para cá, sempre de olho em tudo o que possa saciar a sua inesgotável curiosidade.\n fonte: Joao Bidu");
                    break;

                case 7:

                    if (dia >= 23)
                        Console.WriteLine("Leao: Da mesma forma que o rugido do leão faz a selva tremer, seu magnetismo, seu poder e seu carisma abalam as estruturas astrais! Não por acaso, seu signo é considerado o mais majestoso do Zodíaco, graças à sua personalidade única, que combina talento, exuberância, energia e paixão. Você é uma pessoa corajosa e autoconfiante. Acredita que a natureza está a serviço do seu poder, e que seus desejos são uma espécie de lei. Por isso, quando coloca uma coisa na cabeça, dificilmente muda de ideia. Você quer aquilo com que sonhou e no tempo que determinou. Se algo sai diferente, vira fera! Como é possível alguém não respeitar suas vontades, gente?!? A pulsão do seu desejo só se compara à sua necessidade de reconhecimento. O leão é o rei da selva, certo? Pois é assim que você se sente: um ser humano com centelha divina, um X-Men com habilidades mágicas, que o distinguem do resto dos mortais. Por isso, nada mais justo do que ganhar aplausos da plateia. Afinal de contas, elogios são o oxigênio da sua vida! Assim, não é de espantar que o Sol seja o regente do seu signo. O astro de luz própria, que ilumina os planetas e gera a vida, impulsiona sua força descomunal, assim como o brilho da sua presença marcante. A soberania do astro-rei também se expressa no animal que simboliza seu signo. Pois você sabe que está no topo: lá do alto, Leão transmite os ideais de nobreza e bravura que orientam seu destino. Portanto, ao lidar com esse poder, jamais perca de vista sua responsabilidade: encorajar as pessoas a despertarem a chama que adormece dentro delas. Essa chama é seu norte e também sua coroa, Leão.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Cancer: Sensibilidade, sentimento, saudosismo, intuição, proteção: todas essas cores desenham o seu DNA, Câncer! São as emoções que dão forma aos seus projetos e apontam caminhos, indicando quando e como agir. Portanto, para ser feliz, é imprescindível que o tanque do amor esteja sempre cheio. Amor, no caso, não é apenas o romântico, embora esse tenha um papel fundamental na sua trajetória. De fato, você só se realiza quando encontra sua alma gêmea, mas as outras expressões de afeto também importam, porque ajudam a construir os alicerces da sua felicidade. Assim, se não houver união e carinho no ninho familiar e junto aos seus amigos queridos, nada feito! Seu desejo de segurança afetiva é urgente, porque, sem ela, você perde uma parte significativa da sua identidade. E isso é muito sério. Por isso, seu ideal de vida é curtir uma atmosfera de acolhimento, trocando vibrações de ternura e proteção com quem mora na suíte presidencial do seu coração: mãe, pai, filhos, parceiro(a), irmãos, avós, amigos. Essa natureza sentimental e tão ricamente sensível é um oferecimento da Lua: esse astro, de essência feminina, é quem rege o seu signo. Assim como as fases lunares, seu humor é mutável, bem como a direção da sua energia. De vez em quando, você adora ficar no meio da galera. Outras vezes, prefere se trancar no quarto para meditar. Como o caranguejo que simboliza seu signo, você gruda as pinças na areia para se sentir em casa, junto às raízes, pertinho da água. A mesma Água que embala seus sonhos e conforta sua alma.\n fonte: Joao Bidu");
                    break;

                case 8:

                    if (dia >= 23)
                        Console.WriteLine("Virgem: Por que o símbolo do seu signo é uma jovem segurando uma espiga de trigo? Dizem que esse símbolo entrega a vocação elementar de Virgem: separar o joio do trigo! Cabe a você observar, organizar, classificar, avaliar, julgar. Seus olhos inteligentes e críticos não deixam escapar nada, inclusive quando se posicionam em frente ao espelho. Sim: você é uma pessoa exigente com todo mundo – e mais ainda com si mesma. Uma certeza reina entre as suas convicções: tudo aquilo em que Virgem toca pode melhorar. Daí, seu cuidado com os métodos, sua atenção aos processos e sua fixação no trabalho, no expediente, no ofício. Virgem trabalha muito – e não reclama! Enquanto mede, corta, apara, lixa e lustra as coisas e as pessoas, vai cumprindo seus outros propósitos zodiacais: promover a cura, ajudar a restabelecer a saúde. Cura e saúde não significam aqui, necessariamente, doença e recuperação do corpo físico, e sim das relações humanas e dos ideais de vida. Sua intenção é melhorar tudo o que estiver ao seu alcance, pois acredita que o segredo da felicidade mora aí. E essa tarefa exige disciplina. Por isso é que seu signo tem fama de arrumadinho. As pessoas gostam de brincar que sua gaveta é um capricho e que seu cabelo está sempre alinhado! Muitas vezes, isso é um exagero, porque a organização virginiana pode se relacionar mais à forma de pensar do que ao cuidado com a parte prática da vida. Mas, justiça seja feita: praticidade é uma de suas qualidades marcantes. É um presente de Mercúrio, que rege seu signo e lhe empresta também uma lacradora capacidade de análise.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Leao: Da mesma forma que o rugido do leão faz a selva tremer, seu magnetismo, seu poder e seu carisma abalam as estruturas astrais! Não por acaso, seu signo é considerado o mais majestoso do Zodíaco, graças à sua personalidade única, que combina talento, exuberância, energia e paixão. Você é uma pessoa corajosa e autoconfiante. Acredita que a natureza está a serviço do seu poder, e que seus desejos são uma espécie de lei. Por isso, quando coloca uma coisa na cabeça, dificilmente muda de ideia. Você quer aquilo com que sonhou e no tempo que determinou. Se algo sai diferente, vira fera! Como é possível alguém não respeitar suas vontades, gente?!? A pulsão do seu desejo só se compara à sua necessidade de reconhecimento. O leão é o rei da selva, certo? Pois é assim que você se sente: um ser humano com centelha divina, um X-Men com habilidades mágicas, que o distinguem do resto dos mortais. Por isso, nada mais justo do que ganhar aplausos da plateia. Afinal de contas, elogios são o oxigênio da sua vida! Assim, não é de espantar que o Sol seja o regente do seu signo. O astro de luz própria, que ilumina os planetas e gera a vida, impulsiona sua força descomunal, assim como o brilho da sua presença marcante. A soberania do astro-rei também se expressa no animal que simboliza seu signo. Pois você sabe que está no topo: lá do alto, Leão transmite os ideais de nobreza e bravura que orientam seu destino. Portanto, ao lidar com esse poder, jamais perca de vista sua responsabilidade: encorajar as pessoas a despertarem a chama que adormece dentro delas. Essa chama é seu norte e também sua coroa, Leão.\n fonte: Joao Bidu");
                    break;

                case 9:

                    if (dia >= 23)
                        Console.WriteLine("Libra: Dizem que o primeiro livro de etiqueta do mundo foi escrito por um libriano. Será? O fato é que esse signo é muito educado. Talvez alguns librianos não conheçam a fundo boas maneiras, mas eles sabem se comportar em qualquer ocasião, já que o básico não lhes falta: uma mistura de gentileza, cordialidade, diplomacia e até uma pitada de sofisticação. É possível encontrar tudo isso em Libra, já que esse signo cuida dessas qualidades como um músico toma conta do próprio piano. É ferramenta de trabalho! Os librianos usam essas ferramentas para se aproximar das pessoas e construir relações harmoniosas. Eles são pródigos nisso: além da simpatia natural, são comunicativos, agradáveis, cativantes. Também se revelam ouvintes atentos, que se concentram nas palavras do interlocutor. Qualquer atitude diferente dessa soaria deselegante, e grosseria é uma possibilidade simplesmente impensável para Libra. Mas qual o objetivo de toda essa boa educação? É uma intenção ilustre: semear a cooperação. Libra nasceu para promover os relacionamentos, equilibrar as diferenças, ajustar os contrastes. A reboque disso, vem a ânsia de espalhar a beleza! A devoção ao belo é um presente do seu planeta regente, Vênus, que também confere charme e elegância ao seu jeito de ser. Outra importante característica libriana é a necessidade de justiça. Como a balança que simboliza seu signo, Libra defende a imparcialidade nos julgamentos e o equilíbrio em qualquer situação. Isso faz parte do mundo ideal com que você sonha e que ajuda a estruturar, com seus exemplos incríveis de tolerância, conciliação e colaboração.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Virgem: Por que o símbolo do seu signo é uma jovem segurando uma espiga de trigo? Dizem que esse símbolo entrega a vocação elementar de Virgem: separar o joio do trigo! Cabe a você observar, organizar, classificar, avaliar, julgar. Seus olhos inteligentes e críticos não deixam escapar nada, inclusive quando se posicionam em frente ao espelho. Sim: você é uma pessoa exigente com todo mundo – e mais ainda com si mesma. Uma certeza reina entre as suas convicções: tudo aquilo em que Virgem toca pode melhorar. Daí, seu cuidado com os métodos, sua atenção aos processos e sua fixação no trabalho, no expediente, no ofício. Virgem trabalha muito – e não reclama! Enquanto mede, corta, apara, lixa e lustra as coisas e as pessoas, vai cumprindo seus outros propósitos zodiacais: promover a cura, ajudar a restabelecer a saúde. Cura e saúde não significam aqui, necessariamente, doença e recuperação do corpo físico, e sim das relações humanas e dos ideais de vida. Sua intenção é melhorar tudo o que estiver ao seu alcance, pois acredita que o segredo da felicidade mora aí. E essa tarefa exige disciplina. Por isso é que seu signo tem fama de arrumadinho. As pessoas gostam de brincar que sua gaveta é um capricho e que seu cabelo está sempre alinhado! Muitas vezes, isso é um exagero, porque a organização virginiana pode se relacionar mais à forma de pensar do que ao cuidado com a parte prática da vida. Mas, justiça seja feita: praticidade é uma de suas qualidades marcantes. É um presente de Mercúrio, que rege seu signo e lhe empresta também uma lacradora capacidade de análise.\n fonte: Joao Bidu");
                    break;

                case 10:

                    if (dia >= 23)
                        Console.WriteLine("Escorpião: Na Astrologia, Escorpião é chamado de detetive do Zodíaco. E isso não é exagero: esse signo, realmente, tem a capacidade de investigar as emoções humanas mais profundas. É como um mergulhador diante do oceano: ele quer descobrir as criaturas que vivem lá em baixo, identificar a vegetação, reconhecer as cores, texturas e formas que dançam na água. É tipo um explorador de abismos, sabe? Não por acaso, as emoções de Escorpião são fundas, vastas. Tudo o afeta intensamente, mas esse signo é durão e nem sempre manifesta seus sentimentos e suas impressões. Os escorpianos acham que deixar essa porta aberta é sinônimo de fraqueza. Por isso, por fora, podem parecer tranquilos e sossegados. Por dentro, no entanto, guardam um tsunami em atividade! E é aí que mora seu desafio: radiografar essa vastidão emocional e aprender a transformá-la. Primeiro, é preciso administrar seus sentimentos e suas paixões. Só depois, é possível lapidar todo esse conteúdo para renascer como uma pessoa melhor. Quando isso acontece, você descobre talentos que nem julgava possuir. E pode aplicar essa técnica para auxiliar outras pessoas a também despertarem suas vocações. O que ajuda nesse processo é a Água. Esse elemento lhe confere sensibilidade e intuição, duas das suas qualidades superturbo! E também Plutão, que é o regente do seu signo. Esse astro injeta coragem e perspicácia no seu jeito de ser. E ainda bate as suas emoções no liquidificador! Por isso, você é essa pessoa tão enigmática e fascinante, Escorpião. E também guerreira: assim como o animal escorpião, seu ferrão é poderoso e não dorme nunca.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Libra: Dizem que o primeiro livro de etiqueta do mundo foi escrito por um libriano. Será? O fato é que esse signo é muito educado. Talvez alguns librianos não conheçam a fundo boas maneiras, mas eles sabem se comportar em qualquer ocasião, já que o básico não lhes falta: uma mistura de gentileza, cordialidade, diplomacia e até uma pitada de sofisticação. É possível encontrar tudo isso em Libra, já que esse signo cuida dessas qualidades como um músico toma conta do próprio piano. É ferramenta de trabalho! Os librianos usam essas ferramentas para se aproximar das pessoas e construir relações harmoniosas. Eles são pródigos nisso: além da simpatia natural, são comunicativos, agradáveis, cativantes. Também se revelam ouvintes atentos, que se concentram nas palavras do interlocutor. Qualquer atitude diferente dessa soaria deselegante, e grosseria é uma possibilidade simplesmente impensável para Libra. Mas qual o objetivo de toda essa boa educação? É uma intenção ilustre: semear a cooperação. Libra nasceu para promover os relacionamentos, equilibrar as diferenças, ajustar os contrastes. A reboque disso, vem a ânsia de espalhar a beleza! A devoção ao belo é um presente do seu planeta regente, Vênus, que também confere charme e elegância ao seu jeito de ser. Outra importante característica libriana é a necessidade de justiça. Como a balança que simboliza seu signo, Libra defende a imparcialidade nos julgamentos e o equilíbrio em qualquer situação. Isso faz parte do mundo ideal com que você sonha e que ajuda a estruturar, com seus exemplos incríveis de tolerância, conciliação e colaboração.\n fonte: Joao Bidu");
                    break;

                case 11:

                    if (dia >= 22)
                        Console.WriteLine("Sagitário: Otimismo, autoconfiança, lealdade, energia, generosidade, alegria: são inúmeras as virtudes de Sagitário! Esse signo é o talismã do Zodíaco: a sorte segue os passos dos sagitarianos como uma sombra! Por isso, sua companhia é disputada pelos amigos e colegas de escola, academia ou boteco: graças à sua verdadeira usina interior, você topa todos os programas do mundo! Claro que o prazer que o lazer proporciona interessa a Sagitário, mas há outra razão mais profunda: o sabor irresistível das novas experiências. Você adora conhecer gente, descobrir histórias diferentes, identificar o significado das coisas e das pessoas. Isso porque, enriquecer sua existência é um dos pilares da sua vida, é o que dá sentido à sua jornada. Quando alguém diz que o importante não é chegada nem a partida, e sim a travessia, está se referindo a você e às suas andanças, Sagitário. Por isso mesmo, seu signo é considerado um cidadão do mundo. Preconceitos não fazem parte do seu repertório, muito menos divisas culturais ou religiosas. Sua fome de informação é tanta, que você prefere somar tudo, correr riscos, aventurar-se pelas esquinas do planeta para provar cada pedacinho de vida. Essa disposição inesgotável leva você a abrir seu coração sem medo. Assim, a sinceridade dá o tom às suas palavras: Sagitário raramente mente, mas também quase nunca consegue agir com diplomacia. É um “defeitinho” que pode ser amenizado pela sua generosidade, um presente de Júpiter, que governa seu signo. Planeta da sorte, da expansão e da sabedoria, Júpiter ou Zeus também é o deus supremo na mitologia greco-romana. Não pode ser coincidência!\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Escorpiao: Na Astrologia, Escorpião é chamado de detetive do Zodíaco. E isso não é exagero: esse signo, realmente, tem a capacidade de investigar as emoções humanas mais profundas. É como um mergulhador diante do oceano: ele quer descobrir as criaturas que vivem lá em baixo, identificar a vegetação, reconhecer as cores, texturas e formas que dançam na água. É tipo um explorador de abismos, sabe? Não por acaso, as emoções de Escorpião são fundas, vastas. Tudo o afeta intensamente, mas esse signo é durão e nem sempre manifesta seus sentimentos e suas impressões. Os escorpianos acham que deixar essa porta aberta é sinônimo de fraqueza. Por isso, por fora, podem parecer tranquilos e sossegados. Por dentro, no entanto, guardam um tsunami em atividade! E é aí que mora seu desafio: radiografar essa vastidão emocional e aprender a transformá-la. Primeiro, é preciso administrar seus sentimentos e suas paixões. Só depois, é possível lapidar todo esse conteúdo para renascer como uma pessoa melhor. Quando isso acontece, você descobre talentos que nem julgava possuir. E pode aplicar essa técnica para auxiliar outras pessoas a também despertarem suas vocações. O que ajuda nesse processo é a Água. Esse elemento lhe confere sensibilidade e intuição, duas das suas qualidades superturbo! E também Plutão, que é o regente do seu signo. Esse astro injeta coragem e perspicácia no seu jeito de ser. E ainda bate as suas emoções no liquidificador! Por isso, você é essa pessoa tão enigmática e fascinante, Escorpião. E também guerreira: assim como o animal escorpião, seu ferrão é poderoso e não dorme nunca.\n fonte: Joao Bidu");
                    break;

                case 12:

                    if (dia >= 22)
                        Console.WriteLine("Capricornio: A obstinação é uma palavra que define seu jeito de ser. Porque não há, no mundo, um obstáculo que derrube sua tenacidade, sua perseverança, sua vontade de vencer. Requisitos não lhe faltam: você é uma pessoa prudente, confiável, competente, controlada. Sabe onde pisa, calcula com precisão a largura do seu passo, tem noção exata do que deseja alcançar. Por isso, o trabalho é uma das prioridades da sua vida. É numa profissão que você despeja sua notável capacidade de realização, que consiste em construir e desenvolver ideias, projetos e processos. Tudo isso pode até ser idealizado por terceiros, não tem importância. Seu negócio é colocar a mão na massa, levantar valores, definir recursos, determinar prazos, projetar resultados. Você é quem faz um sonho virar realidade. Sem a força capricorniana, um propósito no papel é só uma possibilidade. Sob o seu comando, as coisas se concretizam, acontecem. Capricórnio é como o gerente da vida! E esse papel de gerente da vida não é gratuito. Seu astro regente é Saturno, o planeta do tempo, da ponderação, da responsabilidade. Esse astro inspira sua maturidade e grita aquele ditado popular na sua alma: “A paciência é a mãe de todas as virtudes!”. Ou seja, com calma, precisão e foco, é possível conquistar o mundo! É claro que isso amplifica sua ambição. Você sonha com poder e sucesso, inclusive material. Mas essa sede de vencer tem um preço: a repressão das suas emoções. Sua fama de signo frio e calculista vem daí. Claro que essa fama é exagerada, Capricórnio, mas sempre é tempo de renovar sua bagagem emocional. O segredo da sua felicidade integral pode morar aí.\n fonte: Joao Bidu");
                    else
                        Console.WriteLine("Sagitario: Otimismo, autoconfiança, lealdade, energia, generosidade, alegria: são inúmeras as virtudes de Sagitário! Esse signo é o talismã do Zodíaco: a sorte segue os passos dos sagitarianos como uma sombra! Por isso, sua companhia é disputada pelos amigos e colegas de escola, academia ou boteco: graças à sua verdadeira usina interior, você topa todos os programas do mundo! Claro que o prazer que o lazer proporciona interessa a Sagitário, mas há outra razão mais profunda: o sabor irresistível das novas experiências. Você adora conhecer gente, descobrir histórias diferentes, identificar o significado das coisas e das pessoas. Isso porque, enriquecer sua existência é um dos pilares da sua vida, é o que dá sentido à sua jornada. Quando alguém diz que o importante não é chegada nem a partida, e sim a travessia, está se referindo a você e às suas andanças, Sagitário. Por isso mesmo, seu signo é considerado um cidadão do mundo. Preconceitos não fazem parte do seu repertório, muito menos divisas culturais ou religiosas. Sua fome de informação é tanta, que você prefere somar tudo, correr riscos, aventurar-se pelas esquinas do planeta para provar cada pedacinho de vida. Essa disposição inesgotável leva você a abrir seu coração sem medo. Assim, a sinceridade dá o tom às suas palavras: Sagitário raramente mente, mas também quase nunca consegue agir com diplomacia. É um “defeitinho” que pode ser amenizado pela sua generosidade, um presente de Júpiter, que governa seu signo. Planeta da sorte, da expansão e da sabedoria, Júpiter ou Zeus também é o deus supremo na mitologia greco-romana. Não pode ser coincidência!\n fonte: Joao Bidu");
                    break;

                default:
                    Console.WriteLine("Esse valor nao e valido");
                    break;
            
                   

            }
                 Console.ReadKey();


        }
    }
}
